os: linux
dist: focal
language: node_js

node_js:
  - "stable"

dist: focal

deploy:
  provider: pages:git
  edge: true
  token: $github_token
  cleanup: false
  local_dir: build
  on:
    branch: main